# Generated by Django 4.1.3 on 2022-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_pic1', models.ImageField(upload_to='land_images/')),
                ('land_pic2', models.ImageField(default='', upload_to='land_images/')),
                ('land_pic3', models.ImageField(default='', upload_to='land_images/')),
                ('land_pic4', models.ImageField(default='', upload_to='land_images/')),
                ('land_pic5', models.ImageField(default='', upload_to='land_images/')),
                ('land_description', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Addplot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_pic1', models.ImageField(upload_to='plot_images/')),
                ('plot_pic2', models.ImageField(default='', upload_to='plot_images/')),
                ('plot_pic3', models.ImageField(default='', upload_to='plot_images/')),
                ('plot_pic4', models.ImageField(default='', upload_to='plot_images/')),
                ('plot_pic5', models.ImageField(default='', upload_to='plot_images/')),
                ('plot_description', models.TextField(max_length=1500)),
            ],
        ),
    ]
